name: blog-school
type: blueprint
author: pizero
depandent: pandoc
copyfile:
  # - docs
  - icons
  # - images
  # - images-share
  - projects
  - style
  - about.html
  - favicon.ico
  - favicon.svg
  - icon.svg
  - more.html
  - search.html
  - searching.html
  - history
doc_blueprint: blog.html
history_blueprint: history/index.html
# build_command: pandoc '{file_path}' -o '{output_path}' --toc --template={doc_blueprint}