name: blog-school
type: blueprint
author: pizero
depandent: pandoc
copyfile:
  - icons
  - images
  - projects
  - style
  - images.html
  - about.html
  - favicon.ico
  - favicon.svg
  - icon.svg
  - more.html
  - search.html
  - searching.html
  - history
doc_blueprint: blog.html
history_blueprint: history/index.html
images_blueprint: images.html
images_block_blueprint: articles/images.html
